services:
  postgres:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    image: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - hana:/var/lib/postgresql/data
  website:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      PASSWORD_HASH: ${PASSWORD_HASH}
      WAIT_HOSTS: postgres:5432
    ports:
      - ${WEBSITE_PORT}:3000
volumes:
  hana:
    external: true
